version: '3'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: anna
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: company_contacts
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: